import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
     title: "ERC-20 Token Lab | Professional Token Management Interface",
  description:
    "Professional smart contract interface for ERC-20 token operations including minting, transfers, burning, and emergency controls. Built with industry-standard security practices.",
   keywords: ["ERC-20", "Token", "Ethereum", "Web3", "Smart Contract", "DeFi"],
   authors: [{ name: "Token Lab" }],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
